version: '2'
services:
  reactivity:
    build: .
    volumes:
     - .:/home/reactivity/reactivity
    environment:
     - REACTIVITY_COUCHBASE_NODES=couchbase
  couchbase:
    image: "couchbase/server:latest"
    ports:
     - "8091-8094:8091-8094"
     - "11210:11210"